; check outport 0xfee1

#org 0x2000
	LDI 0xfe STB 0xffff ; SP initialize
main:
	JPS _Clear CLZ _XPos CLZ _YPos
	CLB outport
loop:
	MIV dat1, PtrD
	LDT PtrD STZ Z1			; number of data bytes
loop1:
	INV PtrD
	LDT PtrD				; get data byte
	STB outport				; output to outport
	
	MIZ 2,Z1+1				; wait 512 ms
loop2:
	LDI 0 JAS delay_ms		; wait 256 ms
	DEZ Z1+1
	BNE loop2

	DEZ Z1
	BNE loop1				; next byte

	JPA loop

; ################################## Subroutines ###################################
; ----------------------------------------------
; delay A * 1 ms
delay_ms:
	PHS			; 8
	MIZ 194,Z0	; 4 ( + 8 ) = 12 * 0,125 = 1,5 µs 
delay1:			; n * 0,125 * (32+5+4) = n * 5,125 µs
	NOP	NOP		; 32
	DEZ Z0		; 5
	BNE delay1	; 4/3 -> 194 * 5,125 = 994,25 - 0,125 = 994,125 µs
	PLS			; 6
	DEC			; 3
	BNE delay_ms	; 4/3
	RTS			; 10 ( + 3 + 3 + 6 ) = 22 * 0,125 = 2,75 + 1,5 µs = 4,25 µs + 994,125 µs + 2 µs (call) = 1000,375s
; ----------------------------------------------

#org 0x2100
data: 6,0x81,0x42,0x24,0x18,0x24,0x42,
dat1: 28,0x01,0x03,0x07,0x0f,0x1f,0x3f,0x7f,0xff,0xfe,0xfc,0xf8,0xf0,0xe0,0xc0,0x80,0xc0,0xe0,0xf0,0xf8,0xfc,0xfe,0xff,0x7f,0x3f,0x1f,0x0f,0x07,0x03,
dat2: 14,0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80,0x40,0x20,0x10,0x08,0x04,0x02,
dat3: 14,0x7f,0xbf,0xdf,0xef,0xf7,0xfb,0xfd,0xfe,0xfd,0xfb,0xf7,0xef,0xdf,0xbf,
dat4: 6,0x7e,0xbd,0xdb,0xe7,0xdb,0xbd,

#mute
#org 0x0000
Z0: 	0x00,
Z1: 	0x0000,
PtrD:	0x0000,

#org 0xfee1	outport:	;
#org 0xfee2	joystick:	;

; MinOS API definitions generated by 'asm os.asm -s_'
#org 0xf000 _Start:
#org 0xf003 _Prompt:
#org 0xf006 _MemMove:
#org 0xf009 _Random:
#org 0xf00c _ScanPS2:
#org 0xf00f _ResetPS2:
#org 0xf012 _ReadInput:
#org 0xf015 _WaitInput:
#org 0xf018 _ReadLine:
#org 0xf01b _SkipSpace:
#org 0xf01e _ReadHex:
#org 0xf021 _SerialWait:
#org 0xf024 _SerialPrint:
#org 0xf027 _FindFile:
#org 0xf02a _LoadFile:
#org 0xf02d _SaveFile:
#org 0xf030 _ClearVRAM:
#org 0xf033 _Clear:
#org 0xf036 _ClearRow:
#org 0xf039 _ScrollUp:
#org 0xf03c _ScrollDn:
#org 0xf03f _Char:
#org 0xf042 _PrintChar:
#org 0xf045 _Print:
#org 0xf048 _PrintPtr:
#org 0xf04b _PrintHex:
#org 0xf04e _SetPixel:
#org 0xf051 _Line:
#org 0xf054 _Rect:
#org 0x00c0 _XPos:
#org 0x00c1 _YPos:
#org 0x00c2 _RandomState:
#org 0x00c6 _ReadNum:
#org 0x00c9 _ReadPtr:
#org 0x00cd _ReadBuffer: