; check kempston joystick

#org 0x2000
	LDI 0xfe STB 0xffff ; SP initialize
main:
	JPS _Clear CLZ _XPos CLZ _YPos
	JPS _Print "Kempston Joystick" , 10, "Port 0xfee2: ", 0
loop:
	MIZ 1,_YPos MIZ 12,_XPos
	LDB joystick STB value
	JAS _PrintHex JPS _Print 10, 0

	JPS _ClearRow
	LDB mask+0 ANB value CPI 0x00
	BNE next1
	JPS _Print "right ", 0
next1:
	LDB mask+1 ANB value CPI 0x00
	BNE next2
	JPS _Print "left ", 0
next2:
	LDB mask+2 ANB value CPI 0x00
	BNE next3
	JPS _Print "down ", 0
next3:
	LDB mask+3 ANB value CPI 0x00
	BNE next4
	JPS _Print "up ", 0
next4:
	LDB mask+4 ANB value CPI 0x00
	BNE next5
	JPS _Print "fire ", 0
next5:
	LDB mask+5 ANB value CPI 0x00
	BNE next6
	JPS _Print "fire2 ", 0
next6:
	LDB mask+6 ANB value CPI 0x00
	BNE next7
	JPS _Print "not available ", 0
next7:
	LDB mask+7 ANB value CPI 0x00
	BNE next8
	JPS _Print "fire3 ", 0
next8:
	LDI 0 JAS delay_ms		; wait 256 ms

	JPA loop

; ################################## Subroutines ###################################
; ----------------------------------------------
; delay A * 1 ms
delay_ms:
	PHS			; 8
	MIZ 194,Z0	; 4 ( + 8 ) = 12 * 0,125 = 1,5 µs 
delay1:			; n * 0,125 * (32+5+4) = n * 5,125 µs
	NOP	NOP		; 32
	DEZ Z0		; 5
	BNE delay1	; 4/3 -> 194 * 5,125 = 994,25 - 0,125 = 994,125 µs
	PLS			; 6
	DEC			; 3
	BNE delay_ms	; 4/3
	RTS			; 10 ( + 3 + 3 + 6 ) = 22 * 0,125 = 2,75 + 1,5 µs = 4,25 µs + 994,125 µs + 2 µs (call) = 1000,375s
; ----------------------------------------------
value:	0x00
mask:
	0x01,	; right
	0x02,	; left
	0x04,	; up
	0x08,	; down
	0x10,	; fire
	0x20,	;
	0x40,	;
	0x80	;

#mute
#org 0x0000
Z0: 	0x00,
Z1: 	0x0000,
PtrD:	0x0000,

#org 0xfee2	joystick:	;

; MinOS API definitions generated by 'asm os.asm -s_'
#org 0xf000 _Start:
#org 0xf003 _Prompt:
#org 0xf006 _MemMove:
#org 0xf009 _Random:
#org 0xf00c _ScanPS2:
#org 0xf00f _ResetPS2:
#org 0xf012 _ReadInput:
#org 0xf015 _WaitInput:
#org 0xf018 _ReadLine:
#org 0xf01b _SkipSpace:
#org 0xf01e _ReadHex:
#org 0xf021 _SerialWait:
#org 0xf024 _SerialPrint:
#org 0xf027 _FindFile:
#org 0xf02a _LoadFile:
#org 0xf02d _SaveFile:
#org 0xf030 _ClearVRAM:
#org 0xf033 _Clear:
#org 0xf036 _ClearRow:
#org 0xf039 _ScrollUp:
#org 0xf03c _ScrollDn:
#org 0xf03f _Char:
#org 0xf042 _PrintChar:
#org 0xf045 _Print:
#org 0xf048 _PrintPtr:
#org 0xf04b _PrintHex:
#org 0xf04e _SetPixel:
#org 0xf051 _Line:
#org 0xf054 _Rect:
#org 0x00c0 _XPos:
#org 0x00c1 _YPos:
#org 0x00c2 _RandomState:
#org 0x00c6 _ReadNum:
#org 0x00c9 _ReadPtr:
#org 0x00cd _ReadBuffer: